name: Selenium CI

on:
  push:
    branches: ['branch/cicd']  # Change to your branch or ['*'] for all
  pull_request:
    branches: ['branch/cicd']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Install Google Chrome
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      # 5. Build Maven project
      - name: Build Project
        run: mvn clean install -DskipTests
        working-directory: seleniumProject   # change if your project folder is different

      # 6. Run Selenium Tests (Headless Chrome)
      - name: Run Selenium Tests
        run: mvn test
        working-directory: seleniumProject
        env:
          JAVA_TOOL_OPTIONS: "-Dwebdriver.chrome.driver=/usr/bin/google-chrome"

      # 7. Archive Test Reports
      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: seleniumProject/target/surefire-reports/
